swagger: '2.0'
info:
  title: Bank Argent API documentation
  description: Contains all available API endpoints in this codebase
  version: '1.0.0'
  termsOfService: 'http://swagger.io/terms/'
host: localhost:3001
basePath: /api/v1
schemes:
  - http
paths:
  /user/login:
    post:
      tags:
        - User Module
      summary: Login
      description: API for Login
      parameters:
        - in: body
          name: body
          description: Login Payload
          required: true
          schema:
            $ref: '#/definitions/Login'
      produces:
        - application/json
      responses:
        '200':
          description: Login Successfully
          schema:
            $ref: '#/definitions/LoginResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
  /user/signup:
    post:
      tags:
        - User Module
      summary: Signup
      description: API for Signup
      parameters:
        - in: body
          name: body
          description: Signup Payload
          required: true
          schema:
            $ref: '#/definitions/User'
      produces:
        - application/json
      responses:
        '200':
          description: Signup Successfully
          schema:
            $ref: '#/definitions/ApiResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
  /user/profile:
    post:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: User Profile API
      description: API for fetching a user profile
      parameters:
        - in: header
          type: string
          name: Authorization
          description: Attach Bearer JWT token
          required: true
      produces:
        - application/json
      responses:
        '200':
          description: User profile retrieved successully
          schema:
            $ref: '#/definitions/ApiResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
    put:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: User Profile API
      description: API for updating a user profile
      parameters:
        - in: header
          type: string
          name: Authorization
          description: Attach Bearer JWT token
          required: true
        - in: body
          name: body
          description: Update user profile attributes
          required: true
          schema:
            $ref: '#/definitions/UserProfile'
      produces:
        - application/json
      responses:
        '200':
          description: User profile retrieved successully
          schema:
            $ref: '#/definitions/ApiResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error

  /user/transaction/{transactionId}:
      put:
        security:
          - Bearer: []
        tags:
          - Transaction
        summary: Update information about a transaction
        description: API for updating a transaction
        parameters:
          - in: header
            type: string
            name: Authorization
            description: Attach Bearer JWT token
            required: true
          - in: body
            name: body
            description:  Update an existent transaction
            required: true
            schema:
              $ref: '#/definitions/informationTransactionResponse'  
        produces:
          - application/json
        responses:
          '200':
            description: transaction information updated successfully
            schema:
              $ref: '#/definitions/TransactionDetailResponse'
          '400':
            description: Invalid Fields
          '404':
            description: transaction is not existing
          '500':
            description: Internal Server Error
      post:
        security:
          - Bearer: []
        tags:
          - Transaction 
        summary: ADD transaction information
        description: API for adding information on a transaction
        parameters:
          - in: header
            type: string
            name: Authorization
            description: Attach Bearer JWT token
            required: true
          - in: body
            name: body
            description: Add information on a transaction
            required: true
            schema:
              $ref: '#/definitions/informationTransactionResponse'
        produces:
          - application/json
        responses:
          '200':
            description: User information retrieved successfully
            schema:
              $ref: '#/definitions/TransactionDetailResponse'
          '400':
            description: Invalid Fields
          '404':
            description: transaction is not existing  
          '500':
            description: Internal Server Error
      delete:
        security:
          - Bearer: []
        tags:
          - Transaction 
        summary: Delete information about a transaction
        description: User Profile Transaction Information Update API
        parameters:
          - in: header
            type: string
            name: Authorization
            description: Attach Bearer JWT token
            required: true
          - in: body
            name: body
            description: transaction information deleted successfully
            required: true
            schema:
              $ref: '#/definitions/informationTransactionResponse'
        produces:
          - application/json
        responses:
          '200':
            description: transaction information deleted successfully
            schema:
              $ref: '#/definitions/TransactionDetailResponse'
          '400':
            description: Invalid Fields
          '404':
            description: transaction is not existing  
          '500':
            description: Internal Server Error
      get:
        security:
          - Bearer: []
        tags:
          - Transaction
        summary: View details of a transaction
        description: API to retrieve transaction information from a user profile
        parameters:
          - in: header
            type: string
            name: Authorization
            description: Attach Bearer JWT token
            required: true
        produces:
          - application/json
        responses:
          '200':
            description: transaction information retrieved successfully
            schema:
              $ref: '#/definitions/TransactionDetailResponse'
          '400':
            description: Invalid Fields
          '404':
            description: transaction is not existing
          '500':
            description: Internal Server Error
  /user/transaction:
      get:
        security:
          - Bearer: []
        tags:
          - Transaction
        summary: View all transactions
        description: API to retrieve transactions from a user 
        parameters:
          - in: header
            type: string
            name: Authorization
            description: Attach Bearer JWT token
            required: true
        produces:
          - application/json
        responses:
          '200':
            description: User profile retrieved successully
            schema:
              $ref: '#/definitions/TransactionResponse'
          '400':
            description: Invalid Fields
          '500':
            description: Internal Server Error

securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header
definitions:
  User:
    properties:
      email:
        type: string
        description: user email
      password:
        type: string
        description: user password
      firstName:
        type: string
        description: user first name
      lastName:
        type: string
        description: user last name
  Login:
    properties:
      email:
        type: string
        description: user email
      password:
        type: string
        description: user password
  ApiResponse:
    type: object
    properties:
      status:
        type: integer
      message:
        type: string
      body:
        type: object
        properties:
          id:
            type: string
          email:
            type: string
  LoginResponse:
    type: object
    properties:
      token:
        type: string
  UserProfile:
    type: object
    properties:
      firstName:
        type: string
      lastName:
        type: string
  
  TransactionDetailResponse:
    type: object
    properties:
      dateTransaction:
        type: string
      description:
        type: string
      amount:
        type: string
      balance:
        type: string
      category:
        type: string 
      notes:
        type: string     
  TransactionResponse:
    type: array
    items:
      $ref: '#/definitions/TransactionDetailResponse'
       
  informationTransactionResponse:
    type: object
    properties:
      category:
        type: string 
      notes:
        type: string         